# Generated by Django 3.0.5 on 2024-01-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='abc@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
