# Generated by Django 3.0.5 on 2024-02-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_auto_20240208_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='returnorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=200)),
                ('Cphone', models.CharField(max_length=20)),
                ('dop', models.DateField()),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
    ]
